FROM ubuntu:18.04

LABEL maintainer='nortlite <zubov@selectel.ru>'

RUN apt-get update && apt-get install python3 python3-dev python3-pip libev-dev locales -y
RUN pip3 install flask bjoern sqlalchemy sqlalchemy_utils pymysql pytest
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

ADD . /app

ENTRYPOINT ["/usr/bin/python3", "/app"]
